# Generated by Django 5.0.1 on 2024-01-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensive',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='expensive',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='expensive',
            name='income',
        ),
    ]
